[package]
name = "ox3000cr-def"
version = "0.1.0"
authors = ["Peng Guanwen <pgw1999@outlook.com>"]

[dependencies]
tokio-core = "*"
futures-await = "*"
hyper = "*"
hyper-tls = "*"
scraper = "*"
itertools = "*"
